### ISSUE TITLE
several potential bugs in the main script

### ISSUE THREAD

**Issue by slowsmile** [julibinho/MobiLLe#1]
Dear MobiLLe developer, thanks for developing the MobiLLe tool as it really is a nice algorithm to efficiently reconstruct BCR lineage. However, I found several bugs during my test use, hopefully this can be corrected for improved user experiences.
1) In the main script Mobille.sh, line 95: the variable name should be OutputPath instead of Outpath
2) Mobille.sh line 117, I thought the logic should be "if [ ! -z $ParameterFile ]", isn't it? It will fill in the arguments if $ParameterFile is provided? Otherwise, the program returns error when running it without parameter file
3) In format_labelling_imgt_airr.py, function dico_V_J_CDR3_format: it might be better to reference the field with AIRR field names instead of index, e.g. "split[header.index('v_call')]", as different programs may have different order of AIRR fields
4) bio.SubsMat module is no longer available in the latest biopython package, so the program constantly collapses if user is using the latest biopython
Thanks
Regards
Xiao

**Comment by julibinho** [comment]
It is not for MobiLLe
