### ISSUE TITLE
Newick format output

### ISSUE THREAD

**Issue by slowsmile** [julibinho/MobiLLe#2]
Hi this is Xiao again, I wonder if MobiLLe could output the cluster in Newick format so that user could easily reconstruct a tree view from the clonal sequences?
Thanks

**Comment by julibinho** [comment]
Dear Xiao,

Thanks a lot for your feedback.
However, MobiLLe did not reconstruct B-cell lineage Trees, so it is not possible to provide output in newick format.
Maybe you are interested in try other tools of our group:
https://github.com/julibinho/ClonalTree
http://www.lcqb.upmc.fr/viclod/

thanks again,

**Comment by slowsmile** [comment]
Thanks a lot Juliana !

Yes ClonalTree is the exact program I want. BTW, this tool appears to be
only applicable to heavy chains, what if I have light chains in the input
as well?

In my case, I have a set of antibody sequences (raised from the same
immunogen) and I would like to generate a phylogenetic tree out of it.
These sequences could include light chains as well.

Thanks a lot
Best
Xiao

**Comment by julibinho** [comment]
Dear Xiao,

SOrry for this delay. In principal, you can use ClonalTree with   light chain sequences. You have just to provide the naive sequence to place the root.

Best regards,
   Juliana

**Comment by slowsmile** [comment]
Thanks a lot, really appreciate your reply!
Xiao

**Comment by julibinho** [comment]
Done.
